
@php
    $role = Auth::user()->role;
@endphp

@if ($role == 'Admin')
    @include('../layout.Admin_header')
@elseif ($role == 'Hr Manager')
    @include('../layout.HRM_header')
@elseif ($role == 'Finance Officer')
    @include('../layout.Finance_header')
@elseif ($role == 'Sales Officer')
    @include('../layout.Sales_header')
@elseif ($role == 'Managing Director')
    @include('../layout.Managing_Director_header')
@elseif ($role == 'Marketing Manager')
    @include('../layout.Marketing_Manager_header')
@elseif ($role == 'Digital Marketing Specialist')
    @include('../layout.Digital_Marketing_Specialist_header')
@elseif ($role == 'Digital Marketing Executive')
    @include('../layout.Digital_Marketing_Executive_header')
@elseif ($role == 'Photographer')
    @include('../layout.Photographer_header')
@elseif ($role == 'Junior Accountant')
    @include('../layout.Junior_Accountant_header')
@elseif ($role == 'Cashier')
    @include('../layout.Cashier_header')
@elseif ($role == 'Contract Administrator')
    @include('../layout.Contract_Administrator_header')
@elseif ($role == 'PRO')
    @include('../layout.PRO_header')
@elseif ($role == 'Web Manager')
    @include('../layout.Web_Manager_header')
@elseif ($role == 'Sales Coordinator')
    @include('../layout.Sales_Coordinator_header')
@elseif ($role == 'Sales Manager')
    @include('../layout.Sales_Manager_header')
@elseif ($role == 'Operations Manager')
    @include('../layout.Operations_Manager_header')
@elseif ($role == 'Operations Supervisor')
    @include('../layout.Operations_Supervisor_header')
@elseif ($role == 'Happiness Consultant')
    @include('../layout.Happiness_Consultant_header')
@elseif ($role == 'Customer Services')
    @include('../layout.Customer_Services_header')
@elseif ($role == 'Archive Clerk')
    @include('../layout.Archive_Clerk_header')
@else
    @include('../layout.Administrator_header')
@endif

