<?php

namespace App\Services;

use Exception;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class ZohoItemService
{
    private string $clientId;
    private string $clientSecret;
    private string $refreshToken;
    private string $organizationId;
    private string $baseUrl;
    private string $accessToken;

    public function __construct()
    {
        $this->clientId        = env('ZOHO_CLIENT_ID');
        $this->clientSecret    = env('ZOHO_CLIENT_SECRET');
        $this->refreshToken    = env('ZOHO_REFRESH_TOKEN');
        $this->organizationId  = env('ZOHO_ORG_ID');
        $this->baseUrl         = 'https://www.zohoapis.com/books/v3';
        $this->accessToken     = $this->fetchAccessToken();
    }

    private function fetchAccessToken(): string
    {
        $response = Http::asForm()->post('https://accounts.zoho.com/oauth/v2/token', [
            'grant_type'    => 'refresh_token',
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'refresh_token' => $this->refreshToken,
        ]);

        if ($response->successful() && isset($response->json()['access_token'])) {
            return $response->json()['access_token'];
        }

        throw new Exception('Failed to fetch Zoho access token.');
    }

    private function buildHeaders(): array
    {
        return [
            'Authorization' => 'Zoho-oauthtoken ' . $this->accessToken,
            'Content-Type'  => 'application/json',
        ];
    }

    private function handleErrorResponse(string $message, $response): void
    {
        $data     = $response->json() ?: [];
        $zohoMsg  = $data['message'] ?? $response->body();

        Log::error("[ZohoItemService] {$message}", [
            'status'   => $response->status(),
            'zoho_msg' => $zohoMsg,
        ]);

        if ($response->status() === 401) {
            $this->accessToken = $this->fetchAccessToken();
            throw new Exception("Authentication failed. Token refreshed. Zoho says: {$zohoMsg}");
        }

        if ($response->status() === 403) {
            throw new Exception("Forbidden: Check permissions. Zoho says: {$zohoMsg}");
        }

        throw new Exception("{$message}. Zoho says: {$zohoMsg}");
    }

    public function createItem(array $itemData): array
    {
        if (empty($itemData['candidate_name'])) {
            throw new Exception('Candidate name is required.');
        }

        $url = "{$this->baseUrl}/items?organization_id={$this->organizationId}";

        $customFields = [
            ['api_name' => 'cf_package',                        'value' => $itemData['cf_package'] ?? ''],
            ['api_name' => 'cf_visa_type',                      'value' => $itemData['cf_visa_type'] ?? ''],
            ['api_name' => 'cf_passport_number',                'value' => $itemData['cf_passport_number'] ?? ''],
            ['api_name' => 'cf_govt_fees',                      'value' => $itemData['cf_govt_fees'] ?? 0],
            ['api_name' => 'cf_nationality',                    'value' => $itemData['cf_nationality'] ?? ''],
            ['api_name' => 'cf_item_number',                    'value' => $itemData['cf_item_number'] ?? ''],
            ['api_name' => 'cf_status',                         'value' => $itemData['cf_status'] ?? ''],
            ['api_name' => 'cf_arrival_status',                 'value' => $itemData['cf_arrival_status'] ?? ''],
            ['api_name' => 'cf_client_final_payment_done',      'value' => $itemData['cf_client_final_payment_done'] ?? ''],
            ['api_name' => 'cf_commission_status',              'value' => $itemData['cf_commission_status'] ?? ''],
        ];

        $payload = [
            'name'          => $itemData['candidate_name'],
            'rate'          => $itemData['rate']        ?? 0,
            'unit'          => $itemData['unit']        ?? 'pcs',
            'sku'           => '',
            'status'        => $itemData['status']      ?? 'active',
            'description'   => $itemData['description'] ?? 'Generated by ERP',
            'custom_fields' => $customFields,
        ];

        $response = Http::withHeaders($this->buildHeaders())->post($url, $payload);

        if ($response->successful()) {
            return $response->json();
        }

        $this->handleErrorResponse('Failed to create item in Zoho', $response);
    }

    public function updateItem(string $itemId, array $itemData): array
    {
        $url = "{$this->baseUrl}/items/{$itemId}?organization_id={$this->organizationId}";

        $customFields = [
            ['api_name' => 'cf_package',                        'value' => $itemData['cf_package'] ?? ''],
            ['api_name' => 'cf_visa_type',                      'value' => $itemData['cf_visa_type'] ?? ''],
            ['api_name' => 'cf_passport_number',                'value' => $itemData['cf_passport_number'] ?? ''],
            ['api_name' => 'cf_govt_fees',                      'value' => $itemData['cf_govt_fees'] ?? 0],
            ['api_name' => 'cf_nationality',                    'value' => $itemData['cf_nationality'] ?? ''],
            ['api_name' => 'cf_item_number',                    'value' => $itemData['cf_item_number'] ?? ''],
            ['api_name' => 'cf_status',                         'value' => $itemData['cf_status'] ?? ''],
            ['api_name' => 'cf_arrival_status',                 'value' => $itemData['cf_arrival_status'] ?? ''],
            ['api_name' => 'cf_client_final_payment_done',      'value' => $itemData['cf_client_final_payment_done'] ?? ''],
            ['api_name' => 'cf_commission_status',              'value' => $itemData['cf_commission_status'] ?? ''],
        ];

        $payload = [
            'name'          => $itemData['candidate_name'] ?? '',
            'rate'          => $itemData['rate']           ?? 0,
            'unit'          => $itemData['unit']           ?? 'pcs',
            'description'   => $itemData['description']    ?? 'Generated by ERP',
            'custom_fields' => $customFields,
        ];

        $response = Http::withHeaders($this->buildHeaders())->put($url, $payload);

        if ($response->successful()) {
            return $response->json();
        }

        $this->handleErrorResponse('Failed to update item in Zoho', $response);
    }

    public function itemExists(string $passportNo): bool
    {
        if (! $passportNo) {
            return false;
        }

        $url      = "{$this->baseUrl}/items?organization_id={$this->organizationId}";
        $response = Http::withHeaders($this->buildHeaders())->get($url);

        if (! $response->successful()) {
            return false;
        }

        $items = $response->json()['items'] ?? [];

        foreach ($items as $item) {
            foreach ($item['custom_fields'] ?? [] as $field) {
                if ($field['api_name'] === 'cf_passport_number' && $field['value'] == $passportNo) {
                    return true;
                }
            }
        }

        return false;
    }
}
